// Public browser config only. Never put a service_role key here.
window.NUONUO_STORE_SUPABASE_URL="PASTE_SUPABASE_URL_HERE";
window.NUONUO_STORE_SUPABASE_ANON_KEY="PASTE_SUPABASE_ANON_KEY_HERE";
window.NUONUO_STORE_OWNER_ID="0d59b9c2-a3c1-4b28-b42f-228082819ade";
